/*Creating the Schema and the tables*/
Drop Schema if Exists assignment;
Create Schema assignment;
Use assignment;

Drop Table if Exists
ACCOUNT_TRANSACTIONS,
ACCOUNT_TRANSACT_TYPES,
ACCOUNT_TYPES,
ACCOUNTS,
ORGANIZATIONS,
PARTIES,
PRODUCTS;

Create Table ACCOUNT_TRANSACTIONS(
ACCTRN_KEY bigint NOT NULL,
ACC_KEY int NOT NULL,
ACCTP_KEY int NOT NULL,
ACTRNTP_KEY int NOT NULL,
ACCTRN_ACCOUNTING_DATE Date NOT NULL,
ACCTRN_AMOUNT_CZK int NOT NULL,
ACCTRN_AMOUNT_FX int NOT NULL,
CURR_ISO_CODE varchar(255) NOT NULL,
ACCTRN_CRDR_FLAG varchar(255) NOT NULL,
ACCTRN_CASH_FLAG varchar(255) NOT NULL,
ACCTRN_INTEREST_FLAG varchar(255) NOT NULL,
ACCTRN_TAX_FLAG varchar(255) NOT NULL,
ACCTRN_FEE_FLAG varchar(255) NOT NULL,
ACC_OTHER_ACCOUNT_KEY int NOT NULL,
ACCTP_OTHER_ACCOUNT_KEY int NOT NULL,
Primary Key(ACCTRN_KEY)
);

Create Table ACCOUNT_TRANSACT_TYPES(
ACTRNTP_KEY int NOT NULL,
ACTRNTP_DESC varchar(255) NOT NULL,
Primary Key(ACTRNTP_KEY)
);

Create Table ACCOUNT_TYPES(
ACCTP_KEY int NOT NULL,
ACCTP_DESC varchar(255),
Primary Key(ACCTP_KEY)
);

Create Table ACCOUNTS(
ACC_KEY int NOT NULL,
ACCTP_KEY int NOT NULL,
PROD_KEY int NOT NULL,
ORG_KEY int NOT NULL,
PT_UNIFIED_KEY bigint NOT NULL,
ACCH_OPEN_DATE date NOT NULL,
ACCH_CLOSE_DATE date NOT NULL,
Primary Key(ACC_KEY)
);

Create Table ORGANIZATIONS(
ORG_KEY int NOT NULL,
ORGH_UNIFIED_ID varchar(255) NOT NULL,
CITY varchar(255) NOT NULL,
ZIP int NOT NULL,
Primary Key(ORG_KEY)
);

Create Table PARTIES(
PT_UNIFIED_KEY int NOT NULL,
ORG_KEY int NOT NULL,
PTH_BIRTH_DATE varchar(255) NOT NULL,
PTH_CLIENT_FROM_DATE varchar(255) NOT NULL,
PTH_CLIENT_FROM_DATE_ALT varchar(255) NOT NULL,
PTTP_UNIFIED_ID varchar(255) NOT NULL,
PSGEN_UNIFIED_ID varchar(255) NOT NULL,
Primary Key(PT_UNIFIED_KEY)
);

Create Table PRODUCTS(
PROD_KEY int NOT NULL,
PROD_AGENDA_CODE varchar(255) NOT NULL,
PROD_AGENDA_NAME varchar(255) NOT NULL,
Primary Key(PROD_KEY)
);